# Generated by Django 6.0.4 on 2026-05-12 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_clothingitem_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Favori mi?'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='max_temp',
            field=models.IntegerField(default=30, verbose_name='Max Derece'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='min_temp',
            field=models.IntegerField(default=0, verbose_name='Min Derece'),
        ),
    ]
