# Generated by Django 6.0.4 on 2026-05-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_clothingitem_is_favorite_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='category',
            field=models.CharField(choices=[('dis', 'Dış Giyim'), ('ust', 'Üst Giyim'), ('alt', 'Alt Giyim'), ('ayakkabi', 'Ayakkabı'), ('aksesuar', 'Aksesuar')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Renk'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
