# Generated by Django 6.0.4 on 2026-05-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_clothingitem_category_alter_clothingitem_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='last_worn',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Giyilme Tarihi'),
        ),
    ]
