# Generated by Django 6.0.4 on 2026-05-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_clothingitem_last_worn'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='style',
            field=models.CharField(choices=[('spor', 'Spor'), ('klasik', 'Klasik'), ('casual', 'Günlük/Casual')], default='casual', max_length=20, verbose_name='Stil'),
        ),
    ]
