# Generated by Django 6.0.4 on 2026-06-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_clothingitem_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='clothing/', verbose_name='Fotoğraf'),
        ),
    ]
