# Generated by Django 6.0.4 on 2026-06-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_clothingitem_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='photo',
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='kiyafetler/', verbose_name='Kıyafet Fotoğrafı'),
        ),
    ]
