# Generated by Django 6.0.4 on 2026-06-04 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_clothingitem_photo_clothingitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='image',
        ),
    ]
